name: docker-homeguard

#===============================================================================
# Networks
#===============================================================================
networks:
  default:
    driver: bridge

#===============================================================================
# Included services
#===============================================================================
include:
  - ./services/ddns-updater/compose.yaml
  - ./services/adguardhome/compose.yaml
  - ./services/wg-easy/compose.yaml
